name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/vector.png
    - assets/page-1/images/vector-Spv.png
    - assets/page-1/images/vector-z4v.png
    - assets/page-1/images/vector-NZk.png
    - assets/page-1/images/vector-QT8.png
    - assets/page-1/images/vector-NCe.png
    - assets/page-1/images/vector-2t6.png
    - assets/page-1/images/vector-n8W.png
    - assets/page-1/images/vector-NJz.png
    - assets/page-1/images/star-5.png
    - assets/page-1/images/batterai.png
    - assets/page-1/images/vector-5Gz.png
    - assets/page-1/images/star-4.png
    - assets/page-1/images/rectangle-22-bg.png
    - assets/page-1/images/vector-T34.png
    - assets/page-1/images/star-2.png
    - assets/page-1/images/rectangle-30.png
    - assets/page-1/images/vector-xaS.png
    - assets/page-1/images/batterai-gdC.png
    - assets/page-1/images/vector-pKQ.png
    - assets/page-1/images/star-3.png
    - assets/page-1/images/vector-Mtr.png
    - assets/page-1/images/vector-mU2.png
    - assets/page-1/images/batterai-U7Y.png
    - assets/page-1/images/.png
    - assets/page-1/images/star-3-GPG.png
    - assets/page-1/images/vector-hSN.png
    - assets/page-1/images/vector-phL.png
    - assets/page-1/images/star-1.png
    - assets/page-1/images/star-1-YEJ.png
    - assets/page-1/images/-Hxa.png
    - assets/page-1/images/vector-TSv.png
    - assets/page-1/images/star-1-oFt.png
    - assets/page-1/images/vector-Gj8.png
    - assets/page-1/images/batterai-WFQ.png
    - assets/page-1/images/vector-rfx.png
    - assets/page-1/images/vector-134.png
    - assets/page-1/images/rectangle-18.png
    - assets/page-1/images/vector-1.png
    - assets/page-1/images/vector-7bt.png
    - assets/page-1/images/rectangle-21.png
    - assets/page-1/images/vector-Qwg.png
    - assets/page-1/images/star-2-Zpa.png
    - assets/page-1/images/star-3-Y2J.png
    - assets/page-1/images/vector-W14.png
    - assets/page-1/images/star-4-7Fk.png
    - assets/page-1/images/vector-qYS.png
    - assets/page-1/images/vector-Yiz.png
    - assets/page-1/images/vector-NEA.png
    - assets/page-1/images/rectangle-30-uzn.png
    - assets/page-1/images/-vgv.png
    - assets/page-1/images/vector-5Zp.png
    - assets/page-1/images/vector-bkS.png
    - assets/page-1/images/star-5-VFU.png
    - assets/page-1/images/vector-X6v.png
    - assets/page-1/images/batterai-VvE.png
    - assets/page-1/images/rectangle-30-BXU.png
    - assets/page-1/images/vector-9vn.png
    - assets/page-1/images/star-1-pn2.png
    - assets/page-1/images/vector-wN6.png
    - assets/page-1/images/vector-tc6.png
    - assets/page-1/images/star-5-V3U.png
    - assets/page-1/images/vector-SCv.png
    - assets/page-1/images/star-5-8ge.png
    - assets/page-1/images/star-2-1VY.png
    - assets/page-1/images/vector-2L6.png
    - assets/page-1/images/star-3-YF8.png
    - assets/page-1/images/vector-p6A.png
    - assets/page-1/images/vector-8aa.png
    - assets/page-1/images/vector-7KL.png
    - assets/page-1/images/vector-zdt.png
    - assets/page-1/images/vector-fNe.png
    - assets/page-1/images/vector-JK8.png
    - assets/page-1/images/vector-9yg.png
    - assets/page-1/images/star-4-U8n.png
    - assets/page-1/images/vector-uE6.png
    - assets/page-1/images/vector-jyp.png
    - assets/page-1/images/vector-MVQ.png
    - assets/page-1/images/vector-LXg.png
    - assets/page-1/images/vector-fkJ.png
    - assets/page-1/images/-3RQ.png
    - assets/page-1/images/vector-bSv.png
    - assets/page-1/images/star-4-5Fc.png
    - assets/page-1/images/vector-XHx.png
    - assets/page-1/images/vector-v6S.png
    - assets/page-1/images/auto-group-ww6e.png
    - assets/page-1/images/auto-group-241c.png
    - assets/page-1/images/vector-f1x.png
    - assets/page-1/images/star-3-TZG.png
    - assets/page-1/images/rectangle-30-A8E.png
    - assets/page-1/images/star-5-soL.png
    - assets/page-1/images/star-1-umx.png
    - assets/page-1/images/vector-43p.png
    - assets/page-1/images/-Zti.png
    - assets/page-1/images/batterai-KRG.png
    - assets/page-1/images/star-2-adL.png
    - assets/page-1/images/batterai-w8S.png
    - assets/page-1/images/vector-YFG.png
    - assets/page-1/images/vector-X7C.png
    - assets/page-1/images/vector-NN2.png
    - assets/page-1/images/vector-SR4.png
    - assets/page-1/images/auto-group-co1g.png
    - assets/page-1/images/vector-My8.png
    - assets/page-1/images/vector-cvz.png
    - assets/page-1/images/vector-hRx.png
    - assets/page-1/images/vector-UFg.png
    - assets/page-1/images/vector-5uY.png
    - assets/page-1/images/vector-3kS.png
    - assets/page-1/images/star-4-hdx.png
    - assets/page-1/images/-UZU.png
    - assets/page-1/images/star-2-mVg.png
    - assets/page-1/images/vector-cJa.png
    - assets/page-1/images/vector-gpe.png
    - assets/page-1/images/vector-15p.png
    - assets/page-1/images/vector-Mtz.png
    - assets/page-1/images/vector-MYr.png
    - assets/page-1/images/-1dx.png
    - assets/page-1/images/vector-Q3p.png
    - assets/page-1/images/rectangle-42-bg.png
    - assets/page-1/images/vector-xUW.png
    - assets/page-1/images/vector-iA2.png
    - assets/page-1/images/vector-LBQ.png
    - assets/page-1/images/vector-qSv.png
    - assets/page-1/images/vector-rKQ.png
    - assets/page-1/images/vector-ncN.png
    - assets/page-1/images/vector-pkW.png
    - assets/page-1/images/vector-FcA.png
    - assets/page-1/images/vector-Mti.png
    - assets/page-1/images/vector-MfU.png
    - assets/page-1/images/rectangle-53.png
    - assets/page-1/images/auto-group-remk.png
    - assets/page-1/images/vector-cHk.png
    - assets/page-1/images/vector-PkA.png
    - assets/page-1/images/vector-pJJ.png
    - assets/page-1/images/-9mp.png
    - assets/page-1/images/vector-PPk.png
    - assets/page-1/images/rectangle-31.png
    - assets/page-1/images/vector-4Y6.png
    - assets/page-1/images/vector-PyY.png
    - assets/page-1/images/batterai-Aj8.png
    - assets/page-1/images/vector-aAa.png
    - assets/page-1/images/vector-w2N.png
    - assets/page-1/images/vector-7MQ.png
    - assets/page-1/images/-Dok.png
    - assets/page-1/images/vector-Xxr.png
    - assets/page-1/images/vector-imc.png
    - assets/page-1/images/vector-dta.png
    - assets/page-1/images/rectangle-53-xwQ.png
    - assets/page-1/images/vector-1ok.png
    - assets/page-1/images/rectangle-73.png
    - assets/page-1/images/-BX4.png
    - assets/page-1/images/auto-group-9mbl.png
    - assets/page-1/images/vector-ebY.png
    - assets/page-1/images/vector-1S6.png
    - assets/page-1/images/vector-ZXU.png
    - assets/page-1/images/rectangle-78.png
    - assets/page-1/images/batterai-TUz.png
    - assets/page-1/images/batterai-DAv.png
    - assets/page-1/images/rectangle-98.png
    - assets/page-1/images/auto-group-rjxa.png
    - assets/page-1/images/vector-QPg.png
    - assets/page-1/images/vector-tCN.png
    - assets/page-1/images/rectangle-88.png
    - assets/page-1/images/star-11.png
    - assets/page-1/images/vector-iDt.png
    - assets/page-1/images/vector-afQ.png
    - assets/page-1/images/vector-Vvn.png
    - assets/page-1/images/star-18.png
    - assets/page-1/images/vector-aPp.png
    - assets/page-1/images/vector-Y5k.png
    - assets/page-1/images/vector-V8i.png
    - assets/page-1/images/auto-group-cxev.png
    - assets/page-1/images/auto-group-rjfc.png
    - assets/page-1/images/rectangle-57.png
    - assets/page-1/images/vector-RMQ.png
    - assets/page-1/images/rectangle-95.png
    - assets/page-1/images/vector-t7x.png
    - assets/page-1/images/batterai-Fga.png
    - assets/page-1/images/star-10.png
    - assets/page-1/images/star-4-YAa.png
    - assets/page-1/images/vector-qCr.png
    - assets/page-1/images/star-8.png
    - assets/page-1/images/rectangle-53-7o4.png
    - assets/page-1/images/vector-91g.png
    - assets/page-1/images/star-7.png
    - assets/page-1/images/vector-Q1U.png
    - assets/page-1/images/star-14.png
    - assets/page-1/images/star-20.png
    - assets/page-1/images/star-13.png
    - assets/page-1/images/vector-vvS.png
    - assets/page-1/images/vector-F7t.png
    - assets/page-1/images/star-1-apN.png
    - assets/page-1/images/vector-nwQ.png
    - assets/page-1/images/-j4J.png
    - assets/page-1/images/vector-qFk.png
    - assets/page-1/images/star-15.png
    - assets/page-1/images/vector-QQe.png
    - assets/page-1/images/vector-Wm4.png
    - assets/page-1/images/rectangle-86.png
    - assets/page-1/images/vector-cr2.png
    - assets/page-1/images/rectangle-99.png
    - assets/page-1/images/rectangle-111.png
    - assets/page-1/images/vector-J1c.png
    - assets/page-1/images/rectangle-85-bg.png
    - assets/page-1/images/rectangle-91.png
    - assets/page-1/images/rectangle-89.png
    - assets/page-1/images/rectangle-79.png
    - assets/page-1/images/rectangle-107.png
    - assets/page-1/images/rectangle-93.png
    - assets/page-1/images/rectangle-92.png
    - assets/page-1/images/rectangle-109.png
    - assets/page-1/images/rectangle-113.png
    - assets/page-1/images/rectangle-97.png
    - assets/page-1/images/star-2-wBk.png
    - assets/page-1/images/vector-W38.png
    - assets/page-1/images/star-19.png
    - assets/page-1/images/star-6.png
    - assets/page-1/images/star-16.png
    - assets/page-1/images/vector-NsY.png
    - assets/page-1/images/batterai-RUS.png
    - assets/page-1/images/star-12.png
    - assets/page-1/images/star-9.png
    - assets/page-1/images/vector-WRt.png
    - assets/page-1/images/star-17.png
    - assets/page-1/images/star-4-eGW.png
    - assets/page-1/images/star-5-XNE.png
    - assets/page-1/images/vector-fDY.png
    - assets/page-1/images/star-2-wwk.png
    - assets/page-1/images/star-1-Nva.png
    - assets/page-1/images/vector-XYa.png
    - assets/page-1/images/star-5-RP4.png
    - assets/page-1/images/vector-xtn.png
    - assets/page-1/images/star-3-7Ft.png
    - assets/page-1/images/vector-TqY.png
    - assets/page-1/images/vector-pcn.png
    - assets/page-1/images/vector-2ir.png
    - assets/page-1/images/vector-JRU.png
    - assets/page-1/images/star-3-qUr.png
    - assets/page-1/images/vector-C2S.png
    - assets/page-1/images/vector-Xin.png
    - assets/page-1/images/vector-th4.png
    - assets/page-1/images/vector-25c.png
    - assets/page-1/images/vector-VQS.png
    - assets/page-1/images/vector-8Lv.png
    - assets/page-1/images/vector-nva.png
    - assets/page-1/images/vector-UXG.png
    - assets/page-1/images/vector-ZCJ.png
    - assets/page-1/images/vector-sy8.png
    - assets/page-1/images/batterai-pjp.png
    - assets/page-1/images/vector-FEn.png
    - assets/page-1/images/-bZY.png
    - assets/page-1/images/vector-A6r.png
    - assets/page-1/images/vector-SVc.png
    - assets/page-1/images/vector-ari.png
    - assets/page-1/images/auto-group-lrje.png
    - assets/page-1/images/vector-73U.png
    - assets/page-1/images/vector-MkA.png
    - assets/page-1/images/vector-6wG.png
    - assets/page-1/images/vector-U5t.png
    - assets/page-1/images/vector-rJi.png
    - assets/page-1/images/vector-xMc.png
    - assets/page-1/images/auto-group-9pyk.png
    - assets/page-1/images/vector-GV4.png
    - assets/page-1/images/vector-hpa.png
    - assets/page-1/images/vector-DwL.png
    - assets/page-1/images/-nUW.png
    - assets/page-1/images/vector-vM4.png
    - assets/page-1/images/vector-bwc.png
    - assets/page-1/images/vector-pdL.png
    - assets/page-1/images/vector-xAS.png
    - assets/page-1/images/auto-group-mwfc.png
    - assets/page-1/images/vector-r6r.png
    - assets/page-1/images/rectangle-30-ewY.png
    - assets/page-1/images/vector-XDp.png
    - assets/page-1/images/vector-q2W.png
    - assets/page-1/images/vector-2Ai.png
    - assets/page-1/images/vector-U3x.png
    - assets/page-1/images/vector-y8J.png
    - assets/page-1/images/vector-qjU.png
    - assets/page-1/images/vector-EYe.png
    - assets/page-1/images/vector-HqY.png
    - assets/page-1/images/vector-h9g.png
    - assets/page-1/images/vector-zfG.png
    - assets/page-1/images/rectangle-57-3BL.png
    - assets/page-1/images/vector-so4.png
    - assets/page-1/images/rectangle-57-Tjt.png
    - assets/page-1/images/vector-Dnv.png
    - assets/page-1/images/vector-QMc.png
    - assets/page-1/images/vector-3Av.png
    - assets/page-1/images/vector-mVY.png
    - assets/page-1/images/vector-qki.png
    - assets/page-1/images/vector-uTU.png
    - assets/page-1/images/vector-V5x.png
    - assets/page-1/images/batterai-BeN.png
    - assets/page-1/images/vector-Dpi.png
    - assets/page-1/images/-XVG.png
    - assets/page-1/images/vector-Ry8.png
    - assets/page-1/images/vector-6rr.png
    - assets/page-1/images/vector-H1G.png
    - assets/page-1/images/rectangle-57-RSn.png
    - assets/page-1/images/rectangle-122.png
    - assets/page-1/images/rectangle-110.png
    - assets/page-1/images/vector-Bfc.png
    - assets/page-1/images/-Rcz.png
    - assets/page-1/images/vector-35x.png
    - assets/page-1/images/vector-B4i.png
    - assets/page-1/images/vector-yKL.png
    - assets/page-1/images/rectangle-116.png
    - assets/page-1/images/rectangle-119.png
    - assets/page-1/images/vector-NkE.png
    - assets/page-1/images/vector-Qra.png
    - assets/page-1/images/vector-5RG.png
    - assets/page-1/images/vector-Yna.png
    - assets/page-1/images/rectangle-107-fNv.png
    - assets/page-1/images/rectangle-113-2fp.png
    - assets/page-1/images/vector-1yg.png
    - assets/page-1/images/vector-Jdt.png
    - assets/page-1/images/vector-yPt.png
    - assets/page-1/images/vector-o4i.png
    - assets/page-1/images/batterai-SAA.png
    - assets/page-1/images/vector-RNn.png
    - assets/page-1/images/vector-foU.png
    - assets/page-1/images/vector-xF8.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
